annotated-types==0.7.0
anyio==4.9.0
attrs==25.3.0
certifi==2025.4.26
cffi==1.17.1
charset-normalizer==3.4.2
clerk-backend-api==2.2.0
click==8.2.1
colorama==0.4.6
cryptography==44.0.3
deprecated==1.2.18
distro==1.9.0
dotenv==0.9.9
fastapi==0.115.12
filelock==3.18.0
fsspec==2025.5.1
greenlet==3.2.2
groq==0.28.0
h11==0.16.0
httpcore==1.0.9
httpx==0.28.1
huggingface-hub==0.33.0
idna==3.10
jiter==0.10.0
openai==1.79.0
packaging==25.0
pycparser==2.22
pydantic==2.11.4
pydantic-core==2.33.2
pyjwt==2.10.1
python-dateutil==2.9.0.post0
python-dotenv==1.1.0
pyyaml==6.0.2
requests==2.32.4
six==1.17.0
sniffio==1.3.1
sqlalchemy==2.0.41
starlette==0.46.2
svix==1.65.0
tqdm==4.67.1
types-deprecated==1.2.15.20250304
types-python-dateutil==2.9.0.20250516
typing-extensions==4.13.2
typing-inspection==0.4.0
urllib3==2.4.0
uvicorn==0.34.2
wrapt==1.17.2
